- name: Instalar HAProxy
  apt:
    name: haproxy
    state: present

- name: Copiar configuración HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Reiniciar HAProxy

- name: Habilitar HAProxy
  systemd:
    name: haproxy
    enabled: yes
    state: started
