- name: Instalar Node.js
  apt:
    name: nodejs
    state: present

- name: Instalar npm
  apt:
    name: npm
    state: present

- name: Crear directorio de la aplicación
  file:
    path: /home/vagrant/app
    state: directory
    owner: vagrant
    group: vagrant

- name: Copiar archivos de la aplicación
  template:
    src: app.js.j2
    dest: /home/vagrant/app/app.js
    owner: vagrant
    group: vagrant

- name: Instalar dependencias
  command: npm install express
  args:
    chdir: /home/vagrant/app

- name: Iniciar el servidor web
  shell: nohup node /home/vagrant/app/app.js > /dev/null 2>&1 &
